## Lab 1: Data in Python

The data for this activity can be downloaded here (under "Data Sets"): https://www.statlearning.com/resources-python

As a first step, create a folder in this location called "data" and drop the Credit.csv file in that location.

If you open the ".gitignore" file, you'll notice that one of the entries is "data" so that your data files will not be shared on GitHub.

In [2]:
import pandas as pd
import numpy as np
Credit = pd.read_csv('data/Credit.csv')
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

### What are the feature names?

In [3]:
Credit.columns

Index(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Own',
       'Student', 'Married', 'Region', 'Balance'],
      dtype='object')

### What are the data types of the feature values (i.e., numeric, categorical)

In [4]:
Credit.dtypes

Income       float64
Limit          int64
Rating         int64
Cards          int64
Age            int64
Education      int64
Own           object
Student       object
Married       object
Region        object
Balance        int64
dtype: object

### Find the mean, median, and mode of the feature "Age."

In [5]:
Credit['Age'].mean()

np.float64(55.6675)

In [6]:
Credit['Age'].median()

56.0

In [7]:
Credit['Age'].mode()

0    44
1    66
Name: Age, dtype: int64

### Create a subset of Credit that only contains the columns Age, Region, and Income. Call it "Subset."

In [24]:
Subset = Credit[['Age', 'Region', 'Income']]
Subset

     Age Region   Income
0     34  South   14.891
1     82   West  106.025
2     71   West  104.593
3     36   West  148.924
4     68  South   55.882
..   ...    ...      ...
395   32  South   12.096
396   65   East   13.364
397   67  South   57.872
398   44  South   37.728
399   64   West   18.701

[400 rows x 3 columns]

### From this subset, create two partitions:
- One that contains records for Ages below 50, and one that contains Ages 50+
- Call them "Younger" and "Older"

In [9]:
Younger = Subset[Subset['Age'] < 50]
Younger

     Age Region   Income
0     34  South   14.891
3     36   West  148.924
6     37   East   20.996
9     41   East   71.061
10    30  South   63.095
..   ...    ...      ...
391   43  South   73.327
392   24   West   25.974
394   40  South   49.794
395   32  South   12.096
398   44  South   37.728

[161 rows x 3 columns]

In [10]:
Older = Subset[Subset['Age'] >= 50]
Older

     Age Region   Income
1     82   West  106.025
2     71   West  104.593
4     68  South   55.882
5     77  South   80.180
7     87   West   71.408
..   ...    ...      ...
390   81   West  135.118
393   65   East   17.316
396   65   East   13.364
397   67  South   57.872
399   64   West   18.701

[239 rows x 3 columns]

### Use these partitions to compare the mean and median Income for each age group (less than 50 vs. 50+)

In [11]:
Younger['Income'].mean()

np.float64(41.65203726708074)

In [12]:
Older['Income'].mean()

np.float64(47.6216569037657)

In [13]:
Younger['Income'].median()

31.861

In [14]:
Older['Income'].median()

33.694

### What does the difference between mean and median suggest about the distribution of income?

The mean is higher than the median for both age groups. This suggests that the income distribution is right-skewed because some people have unusually high incomes that pull the mean upward.

### What are the possible values for Region?

In [15]:
Credit['Region'].unique()

array(['South', 'West', 'East'], dtype=object)

### Use the value_counts method to build a frequency table for the possible values of Region.

In [16]:
Credit['Region'].value_counts()

Region
South    199
West     102
East      99
Name: count, dtype: int64

### Compare the average income for students vs. non-students.

In [17]:
Students = Credit[Credit['Student'] == 'Yes']
Students

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
9,71.061,6819,491,3,41,19,Yes,Yes,Yes,East,1350
26,42.471,3625,289,6,44,12,Yes,Yes,No,South,654
35,23.350,2558,220,3,49,12,Yes,Yes,No,South,419
41,113.659,7659,538,2,66,15,No,Yes,Yes,East,1155
46,19.531,5043,376,2,64,16,Yes,Yes,Yes,West,1241
47,44.646,4431,320,2,49,15,No,Yes,Yes,South,797
49,43.479,4569,354,4,49,13,No,Yes,Yes,East,902
76,30.622,3293,251,1,68,16,No,Yes,No,South,532
96,14.312,5382,367,1,59,17,No,Yes,No,West,1380
98,36.295,2963,241,2,68,14,Yes,Yes,No,East,375
101,17.976,2433,190,3,70,16,Yes,Yes,No,South,431
102,68.713,7582,531,2,56,16,No,Yes,No,South,1587
126,26.427,5533,433,5,50,15,Yes,Yes,Yes,West,1404
128,123.299,8376,610,2,89,17,No,Yes,No,East,1259
130,23.793,3821,281,4,56,12,Yes,Yes,Yes,East,868
140,39.831,6045,459,3,32,12,Yes,Yes,Yes,East,1425
152,41.419,2120,184,4,24,11,Yes,Yes,No,South,156
157,56.256,5521,406,2,72,16,Yes,Yes,Yes,South,1020
191,124.290,9560,701,3,52,17,Yes,Yes,No,West,1687
203,68.206,6784,499,5,40,16,Yes,Yes,No,East,1411
207,10.842,4391,358,5,37,10,Yes,Yes,Yes,South,1216
218,10.627,1647,149,2,71,10,Yes,Yes,Yes,West,195
220,44.847,5765,437,3,53,13,Yes,Yes,No,West,1246
222,33.437,6207,451,4,44,9,No,Yes,No,South,1549
242,20.918,1233,128,3,47,18,Yes,Yes,Yes,West,16
248,15.717,905,93,1,38,16,No,Yes,Yes,South,0
249,22.574,1551,134,3,43,13,Yes,Yes,Yes,South,98
261,180.379,9310,665,3,67,8,Yes,Yes,Yes,West,1050
272,30.413,3690,299,2,25,15,Yes,Yes,No,West,728
273,16.751,4706,353,6,48,14,No,Yes,No,West,1255
279,54.319,3063,248,3,59,8,Yes,Yes,No,South,269
310,33.694,4891,369,1,52,16,No,Yes,No,East,1036
320,16.279,1160,126,3,78,13,No,Yes,Yes,East,5
324,31.029,2863,223,2,66,17,No,Yes,Yes,West,415
330,20.405,4543,329,2,72,17,No,Yes,No,West,1054
365,113.772,6442,489,4,69,15,No,Yes,Yes,South,790
372,19.782,3782,293,2,46,16,Yes,Yes,No,South,840
373,55.412,5354,383,2,37,16,Yes,Yes,Yes,South,1003
382,24.824,5495,409,1,33,9,No,Yes,No,South,1352

In [18]:
Students['Income'].mean()

np.float64(47.29205)

In [19]:
NonStudents = Credit[Credit['Student'] == 'No']
NonStudents

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
5,80.180,8047,569,4,77,10,No,No,No,South,1151
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

In [20]:
NonStudents['Income'].mean()

np.float64(44.988533333333336)

Often, banks will use a variable called _utilization_ to assess credit risk.
Utilization is the ratio of balance to limit (i.e., what % of the credit limit is being used?)
### Add a feature to the Credit dataset to measure utilization

In [21]:
Credit['Utilization'] = Credit['Balance'] / Credit['Limit']
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance,Utilization
0,14.891,3606,283,2,34,11,No,No,Yes,South,333,0.092346
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903,0.135892
2,104.593,7075,514,4,71,11,No,No,No,West,580,0.081979
3,148.924,9504,681,3,36,11,Yes,No,No,West,964,0.101431
4,55.882,4897,357,2,68,16,No,No,Yes,South,331,0.067592
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560,0.136585
396,13.364,3838,296,5,65,17,No,No,No,East,480,0.125065
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138,0.033086
398,37.728,2525,192,1,44,13,No,No,Yes,South,0,0.000000
399,18.701,5524,415,5,64,7,Yes,No,No,West,966,0.174873

In [22]:
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance,Utilization
0,14.891,3606,283,2,34,11,No,No,Yes,South,333,0.092346
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903,0.135892
2,104.593,7075,514,4,71,11,No,No,No,West,580,0.081979
3,148.924,9504,681,3,36,11,Yes,No,No,West,964,0.101431
4,55.882,4897,357,2,68,16,No,No,Yes,South,331,0.067592
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560,0.136585
396,13.364,3838,296,5,65,17,No,No,No,East,480,0.125065
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138,0.033086
398,37.728,2525,192,1,44,13,No,No,Yes,South,0,0.000000
399,18.701,5524,415,5,64,7,Yes,No,No,West,966,0.174873

### What is the maximum utilization value in this set?

In [23]:
Credit['Utilization'].max()

0.27693008426326576